--[[
    EnumData - Shared enum definitions for WoW 3.3.5 (TrinityCore)

    Contains spell effects, aura types, mechanics, targets, etc.
    Used with CreateEnumSelector for searchable dropdowns.
]]

local AIO = AIO or require("AIO")
if AIO.AddAddon() then return end

-- Initialize global enum data table
_G.ENUM_DATA = _G.ENUM_DATA or {}

-- ============================================================================
-- SPELL EFFECT TYPES (SpellEffectNames from 3.3.5)
-- ============================================================================
_G.ENUM_DATA.SPELL_EFFECTS = {
    { id = 0, name = "NONE", desc = "No effect", category = "MISC" },
    { id = 1, name = "INSTAKILL", desc = "Instantly kills the target", category = "DAMAGE" },
    { id = 2, name = "SCHOOL_DAMAGE", desc = "Deals school damage", category = "DAMAGE" },
    { id = 3, name = "DUMMY", desc = "Dummy effect for scripting", category = "MISC" },
    { id = 4, name = "PORTAL_TELEPORT", desc = "Unused portal teleport", category = "TELEPORT" },
    { id = 5, name = "TELEPORT_UNITS", desc = "Teleports units", category = "TELEPORT" },
    { id = 6, name = "APPLY_AURA", desc = "Apply aura effect (see EffectAura field)", category = "AURA" },
    { id = 7, name = "ENVIRONMENTAL_DAMAGE", desc = "Environmental damage (fire, lava, etc)", category = "DAMAGE" },
    { id = 8, name = "POWER_DRAIN", desc = "Drains power from target", category = "POWER" },
    { id = 9, name = "HEALTH_LEECH", desc = "Leeches health from target", category = "HEAL" },
    { id = 10, name = "HEAL", desc = "Heals the target", category = "HEAL" },
    { id = 11, name = "BIND", desc = "Binds player to location", category = "MISC" },
    { id = 12, name = "PORTAL", desc = "Creates a portal", category = "TELEPORT" },
    { id = 13, name = "RITUAL_BASE", desc = "Ritual base effect", category = "MISC" },
    { id = 14, name = "RITUAL_SPECIALIZE", desc = "Ritual specialization", category = "MISC" },
    { id = 15, name = "RITUAL_ACTIVATE_PORTAL", desc = "Activates ritual portal", category = "TELEPORT" },
    { id = 16, name = "QUEST_COMPLETE", desc = "Completes a quest", category = "QUEST" },
    { id = 17, name = "WEAPON_DAMAGE_NOSCHOOL", desc = "Weapon damage (no school)", category = "DAMAGE" },
    { id = 18, name = "RESURRECT", desc = "Resurrects target", category = "HEAL" },
    { id = 19, name = "ADD_EXTRA_ATTACKS", desc = "Adds extra attacks", category = "COMBAT" },
    { id = 20, name = "DODGE", desc = "Dodge effect", category = "COMBAT" },
    { id = 21, name = "EVADE", desc = "Evade effect", category = "COMBAT" },
    { id = 22, name = "PARRY", desc = "Parry effect", category = "COMBAT" },
    { id = 23, name = "BLOCK", desc = "Block effect", category = "COMBAT" },
    { id = 24, name = "CREATE_ITEM", desc = "Creates an item", category = "ITEM" },
    { id = 25, name = "WEAPON", desc = "Weapon effect", category = "COMBAT" },
    { id = 26, name = "DEFENSE", desc = "Defense effect", category = "COMBAT" },
    { id = 27, name = "PERSISTENT_AREA_AURA", desc = "Persistent area aura effect", category = "AURA" },
    { id = 28, name = "SUMMON", desc = "Summons a creature", category = "SUMMON" },
    { id = 29, name = "LEAP", desc = "Leap to target", category = "MOVEMENT" },
    { id = 30, name = "ENERGIZE", desc = "Restores power/energy", category = "POWER" },
    { id = 31, name = "WEAPON_PERCENT_DAMAGE", desc = "Weapon damage (percentage)", category = "DAMAGE" },
    { id = 32, name = "TRIGGER_MISSILE", desc = "Triggers a missile", category = "MISC" },
    { id = 33, name = "OPEN_LOCK", desc = "Opens a lock", category = "MISC" },
    { id = 34, name = "SUMMON_CHANGE_ITEM", desc = "Transform/change item", category = "ITEM" },
    { id = 35, name = "APPLY_AREA_AURA_PARTY", desc = "Apply area aura to party members", category = "AURA" },
    { id = 36, name = "LEARN_SPELL", desc = "Teaches a spell", category = "LEARN" },
    { id = 37, name = "SPELL_DEFENSE", desc = "Spell defense effect", category = "COMBAT" },
    { id = 38, name = "DISPEL", desc = "Dispels effects", category = "DISPEL" },
    { id = 39, name = "LANGUAGE", desc = "Language effect", category = "MISC" },
    { id = 40, name = "DUAL_WIELD", desc = "Enables dual wield", category = "COMBAT" },
    { id = 41, name = "JUMP", desc = "Jump effect", category = "MOVEMENT" },
    { id = 42, name = "JUMP_DEST", desc = "Jump to destination", category = "MOVEMENT" },
    { id = 43, name = "TELEPORT_UNITS_FACE_CASTER", desc = "Teleport facing caster", category = "TELEPORT" },
    { id = 44, name = "SKILL_STEP", desc = "Skill step effect", category = "LEARN" },
    { id = 45, name = "ADD_HONOR", desc = "Adds honor points", category = "MISC" },
    { id = 46, name = "SPAWN", desc = "Spawn effect", category = "SUMMON" },
    { id = 47, name = "TRADE_SKILL", desc = "Trade skill effect", category = "LEARN" },
    { id = 48, name = "STEALTH", desc = "Stealth effect", category = "MISC" },
    { id = 49, name = "DETECT", desc = "Detection effect", category = "MISC" },
    { id = 50, name = "TRANS_DOOR", desc = "Summon object (door)", category = "SUMMON" },
    { id = 51, name = "FORCE_CRITICAL_HIT", desc = "Forces critical hit", category = "COMBAT" },
    { id = 52, name = "GUARANTEE_HIT", desc = "Guarantees hit", category = "COMBAT" },
    { id = 53, name = "ENCHANT_ITEM", desc = "Enchants an item", category = "ITEM" },
    { id = 54, name = "ENCHANT_ITEM_TEMPORARY", desc = "Temporary item enchant", category = "ITEM" },
    { id = 55, name = "TAMECREATURE", desc = "Tames a creature", category = "MISC" },
    { id = 56, name = "SUMMON_PET", desc = "Summons a pet", category = "SUMMON" },
    { id = 57, name = "LEARN_PET_SPELL", desc = "Pet learns spell", category = "LEARN" },
    { id = 58, name = "WEAPON_DAMAGE", desc = "Weapon damage", category = "DAMAGE" },
    { id = 59, name = "CREATE_RANDOM_ITEM", desc = "Creates random item", category = "ITEM" },
    { id = 60, name = "PROFICIENCY", desc = "Grants proficiency", category = "LEARN" },
    { id = 61, name = "SEND_EVENT", desc = "Sends an event", category = "MISC" },
    { id = 62, name = "POWER_BURN", desc = "Burns target power", category = "POWER" },
    { id = 63, name = "THREAT", desc = "Modifies threat", category = "COMBAT" },
    { id = 64, name = "TRIGGER_SPELL", desc = "Triggers another spell", category = "TRIGGER" },
    { id = 65, name = "APPLY_AREA_AURA_RAID", desc = "Apply area aura to raid members", category = "AURA" },
    { id = 66, name = "CREATE_MANA_GEM", desc = "Creates mana gem", category = "ITEM" },
    { id = 67, name = "HEAL_MAX_HEALTH", desc = "Heals to max health", category = "HEAL" },
    { id = 68, name = "INTERRUPT_CAST", desc = "Interrupts casting", category = "COMBAT" },
    { id = 69, name = "DISTRACT", desc = "Distracts target", category = "CONTROL" },
    { id = 70, name = "PULL", desc = "Pulls target", category = "MOVEMENT" },
    { id = 71, name = "PICKPOCKET", desc = "Pickpocket effect", category = "MISC" },
    { id = 72, name = "ADD_FARSIGHT", desc = "Adds farsight", category = "MISC" },
    { id = 73, name = "UNTRAIN_TALENTS", desc = "Untrains talents", category = "LEARN" },
    { id = 74, name = "APPLY_GLYPH", desc = "Applies glyph", category = "LEARN" },
    { id = 75, name = "HEAL_MECHANICAL", desc = "Heals mechanical units", category = "HEAL" },
    { id = 76, name = "SUMMON_OBJECT_WILD", desc = "Summons wild object", category = "SUMMON" },
    { id = 77, name = "SCRIPT_EFFECT", desc = "Script effect (custom)", category = "SCRIPT" },
    { id = 78, name = "ATTACK", desc = "Attack effect", category = "COMBAT" },
    { id = 79, name = "SANCTUARY", desc = "Sanctuary effect", category = "MISC" },
    { id = 80, name = "ADD_COMBO_POINTS", desc = "Adds combo points", category = "COMBAT" },
    { id = 81, name = "CREATE_HOUSE", desc = "Creates house object", category = "SUMMON" },
    { id = 82, name = "BIND_SIGHT", desc = "Binds sight to target", category = "MISC" },
    { id = 83, name = "DUEL", desc = "Initiates duel", category = "MISC" },
    { id = 84, name = "STUCK", desc = "Unstuck effect", category = "MISC" },
    { id = 85, name = "SUMMON_PLAYER", desc = "Summons a player", category = "SUMMON" },
    { id = 86, name = "ACTIVATE_OBJECT", desc = "Activates game object", category = "MISC" },
    { id = 87, name = "GAMEOBJECT_DAMAGE", desc = "Damages game object", category = "DAMAGE" },
    { id = 88, name = "GAMEOBJECT_REPAIR", desc = "Repairs game object", category = "HEAL" },
    { id = 89, name = "GAMEOBJECT_SET_DESTRUCTION_STATE", desc = "Sets GO destruction state", category = "MISC" },
    { id = 90, name = "KILL_CREDIT", desc = "Gives kill credit", category = "QUEST" },
    { id = 91, name = "THREAT_ALL", desc = "Threat to all enemies", category = "COMBAT" },
    { id = 92, name = "ENCHANT_HELD_ITEM", desc = "Enchants held item", category = "ITEM" },
    { id = 93, name = "FORCE_DESELECT", desc = "Forces deselect", category = "CONTROL" },
    { id = 94, name = "SELF_RESURRECT", desc = "Self resurrection", category = "HEAL" },
    { id = 95, name = "SKINNING", desc = "Skinning effect", category = "MISC" },
    { id = 96, name = "CHARGE", desc = "Charge at target", category = "MOVEMENT" },
    { id = 97, name = "CAST_BUTTON", desc = "Cast button spell", category = "MISC" },
    { id = 98, name = "KNOCK_BACK", desc = "Knocks back target", category = "MOVEMENT" },
    { id = 99, name = "DISENCHANT", desc = "Disenchants item", category = "ITEM" },
    { id = 100, name = "INEBRIATE", desc = "Makes target drunk", category = "MISC" },
    { id = 101, name = "FEED_PET", desc = "Feeds pet", category = "MISC" },
    { id = 102, name = "DISMISS_PET", desc = "Dismisses pet", category = "SUMMON" },
    { id = 103, name = "REPUTATION", desc = "Modifies reputation", category = "MISC" },
    { id = 104, name = "SUMMON_OBJECT_SLOT1", desc = "Summons object slot 1", category = "SUMMON" },
    { id = 105, name = "SUMMON_OBJECT_SLOT2", desc = "Summons object slot 2", category = "SUMMON" },
    { id = 106, name = "SUMMON_OBJECT_SLOT3", desc = "Summons object slot 3", category = "SUMMON" },
    { id = 107, name = "SUMMON_OBJECT_SLOT4", desc = "Summons object slot 4", category = "SUMMON" },
    { id = 108, name = "DISPEL_MECHANIC", desc = "Dispels mechanic", category = "DISPEL" },
    { id = 109, name = "SUMMON_DEAD_PET", desc = "Resurrects dead pet", category = "SUMMON" },
    { id = 110, name = "DESTROY_ALL_TOTEMS", desc = "Destroys all totems", category = "MISC" },
    { id = 111, name = "DURABILITY_DAMAGE", desc = "Damages durability", category = "MISC" },
    { id = 112, name = "112", desc = "Effect 112", category = "MISC" },
    { id = 113, name = "RESURRECT_NEW", desc = "Resurrect (new)", category = "HEAL" },
    { id = 114, name = "ATTACK_ME", desc = "Forces attack on caster", category = "CONTROL" },
    { id = 115, name = "DURABILITY_DAMAGE_PCT", desc = "Durability damage percent", category = "MISC" },
    { id = 116, name = "SKIN_PLAYER_CORPSE", desc = "Skins player corpse", category = "MISC" },
    { id = 117, name = "SPIRIT_HEAL", desc = "Spirit healer effect", category = "HEAL" },
    { id = 118, name = "SKILL", desc = "Skill effect", category = "LEARN" },
    { id = 119, name = "APPLY_AREA_AURA_PET", desc = "Apply area aura to pet", category = "AURA" },
    { id = 120, name = "TELEPORT_GRAVEYARD", desc = "Teleport to graveyard", category = "TELEPORT" },
    { id = 121, name = "NORMALIZED_WEAPON_DMG", desc = "Normalized weapon damage", category = "DAMAGE" },
    { id = 122, name = "122", desc = "Effect 122", category = "MISC" },
    { id = 123, name = "SEND_TAXI", desc = "Sends on taxi", category = "TELEPORT" },
    { id = 124, name = "PULL_TOWARDS", desc = "Pulls towards caster", category = "MOVEMENT" },
    { id = 125, name = "MODIFY_THREAT_PERCENT", desc = "Modifies threat percent", category = "COMBAT" },
    { id = 126, name = "STEAL_BENEFICIAL_BUFF", desc = "Steals beneficial buff", category = "DISPEL" },
    { id = 127, name = "PROSPECTING", desc = "Prospecting effect", category = "MISC" },
    { id = 128, name = "APPLY_AREA_AURA_FRIEND", desc = "Apply area aura to friendly units", category = "AURA" },
    { id = 129, name = "APPLY_AREA_AURA_ENEMY", desc = "Apply area aura to enemy units", category = "AURA" },
    { id = 130, name = "REDIRECT_THREAT", desc = "Redirects threat", category = "COMBAT" },
    { id = 131, name = "PLAY_SOUND", desc = "Plays a sound", category = "MISC" },
    { id = 132, name = "PLAY_MUSIC", desc = "Plays music", category = "MISC" },
    { id = 133, name = "UNLEARN_SPECIALIZATION", desc = "Unlearns specialization", category = "LEARN" },
    { id = 134, name = "KILL_CREDIT2", desc = "Kill credit (type 2)", category = "QUEST" },
    { id = 135, name = "CALL_PET", desc = "Calls pet", category = "SUMMON" },
    { id = 136, name = "HEAL_PCT", desc = "Heals percentage of health", category = "HEAL" },
    { id = 137, name = "ENERGIZE_PCT", desc = "Restores percentage of power", category = "POWER" },
    { id = 138, name = "LEAP_BACK", desc = "Leaps backward", category = "MOVEMENT" },
    { id = 139, name = "CLEAR_QUEST", desc = "Clears quest", category = "QUEST" },
    { id = 140, name = "FORCE_CAST", desc = "Forces target to cast", category = "TRIGGER" },
    { id = 141, name = "FORCE_CAST_WITH_VALUE", desc = "Force cast with value", category = "TRIGGER" },
    { id = 142, name = "TRIGGER_SPELL_WITH_VALUE", desc = "Triggers spell with value", category = "TRIGGER" },
    { id = 143, name = "APPLY_AREA_AURA_OWNER", desc = "Apply area aura to owner", category = "AURA" },
    { id = 144, name = "KNOCK_BACK_DEST", desc = "Knockback to destination", category = "MOVEMENT" },
    { id = 145, name = "PULL_TOWARDS_DEST", desc = "Pull towards destination", category = "MOVEMENT" },
    { id = 146, name = "ACTIVATE_RUNE", desc = "Activates rune", category = "MISC" },
    { id = 147, name = "QUEST_FAIL", desc = "Fails a quest", category = "QUEST" },
    { id = 148, name = "TRIGGER_MISSILE_SPELL_WITH_VALUE", desc = "Trigger missile with value", category = "TRIGGER" },
    { id = 149, name = "CHARGE_DEST", desc = "Charge to destination", category = "MOVEMENT" },
    { id = 150, name = "QUEST_START", desc = "Starts a quest", category = "QUEST" },
    { id = 151, name = "TRIGGER_SPELL_2", desc = "Trigger spell (type 2)", category = "TRIGGER" },
    { id = 152, name = "SUMMON_RAF_FRIEND", desc = "Summon RAF friend", category = "SUMMON" },
    { id = 153, name = "CREATE_TAMED_PET", desc = "Creates tamed pet", category = "SUMMON" },
    { id = 154, name = "DISCOVER_TAXI", desc = "Discovers taxi node", category = "MISC" },
    { id = 155, name = "TITAN_GRIP", desc = "Titan's Grip effect", category = "COMBAT" },
    { id = 156, name = "ENCHANT_ITEM_PRISMATIC", desc = "Prismatic enchant", category = "ITEM" },
    { id = 157, name = "CREATE_ITEM_2", desc = "Create item (type 2)", category = "ITEM" },
    { id = 158, name = "MILLING", desc = "Milling effect", category = "MISC" },
    { id = 159, name = "ALLOW_RENAME_PET", desc = "Allows pet rename", category = "MISC" },
    { id = 160, name = "160", desc = "Effect 160", category = "MISC" },
    { id = 161, name = "TALENT_SPEC_COUNT", desc = "Talent spec count", category = "LEARN" },
    { id = 162, name = "TALENT_SPEC_SELECT", desc = "Select talent spec", category = "LEARN" },
    { id = 163, name = "163", desc = "Effect 163", category = "MISC" },
    { id = 164, name = "REMOVE_AURA", desc = "Remove aura from target", category = "DISPEL" },
}

-- ============================================================================
-- AURA TYPES (SpellAuraNames from 3.3.5)
-- ============================================================================
_G.ENUM_DATA.AURA_TYPES = {
    { id = 0, name = "NONE", desc = "No aura", category = "MISC" },
    { id = 1, name = "BIND_SIGHT", desc = "Binds sight to target", category = "CONTROL" },
    { id = 2, name = "MOD_POSSESS", desc = "Possess target", category = "CONTROL" },
    { id = 3, name = "PERIODIC_DAMAGE", desc = "Periodic damage (DoT)", category = "DAMAGE" },
    { id = 4, name = "DUMMY", desc = "Dummy aura for scripting", category = "MISC" },
    { id = 5, name = "MOD_CONFUSE", desc = "Confuse target", category = "CONTROL" },
    { id = 6, name = "MOD_CHARM", desc = "Charm target", category = "CONTROL" },
    { id = 7, name = "MOD_FEAR", desc = "Fear target", category = "CONTROL" },
    { id = 8, name = "PERIODIC_HEAL", desc = "Periodic healing (HoT)", category = "HEAL" },
    { id = 9, name = "MOD_ATTACKSPEED", desc = "Modify attack speed", category = "STAT" },
    { id = 10, name = "MOD_THREAT", desc = "Modify threat", category = "COMBAT" },
    { id = 11, name = "MOD_TAUNT", desc = "Taunt effect", category = "COMBAT" },
    { id = 12, name = "MOD_STUN", desc = "Stun target", category = "CONTROL" },
    { id = 13, name = "MOD_DAMAGE_DONE", desc = "Modify damage done", category = "DAMAGE" },
    { id = 14, name = "MOD_DAMAGE_TAKEN", desc = "Modify damage taken", category = "DAMAGE" },
    { id = 15, name = "DAMAGE_SHIELD", desc = "Damage shield (thorns)", category = "DAMAGE" },
    { id = 16, name = "MOD_STEALTH", desc = "Stealth effect", category = "MISC" },
    { id = 17, name = "MOD_STEALTH_DETECT", desc = "Stealth detection", category = "MISC" },
    { id = 18, name = "MOD_INVISIBILITY", desc = "Invisibility effect", category = "MISC" },
    { id = 19, name = "MOD_INVISIBILITY_DETECT", desc = "Invisibility detection", category = "MISC" },
    { id = 20, name = "OBS_MOD_HEALTH", desc = "Health regen (observation)", category = "HEAL" },
    { id = 21, name = "OBS_MOD_POWER", desc = "Power regen (observation)", category = "POWER" },
    { id = 22, name = "MOD_RESISTANCE", desc = "Modify resistance", category = "STAT" },
    { id = 23, name = "PERIODIC_TRIGGER_SPELL", desc = "Periodic spell trigger", category = "TRIGGER" },
    { id = 24, name = "PERIODIC_ENERGIZE", desc = "Periodic power restore", category = "POWER" },
    { id = 25, name = "MOD_PACIFY", desc = "Pacify target", category = "CONTROL" },
    { id = 26, name = "MOD_ROOT", desc = "Root target", category = "CONTROL" },
    { id = 27, name = "MOD_SILENCE", desc = "Silence target", category = "CONTROL" },
    { id = 28, name = "REFLECT_SPELLS", desc = "Reflect spells", category = "COMBAT" },
    { id = 29, name = "MOD_STAT", desc = "Modify stat", category = "STAT" },
    { id = 30, name = "MOD_SKILL", desc = "Modify skill", category = "STAT" },
    { id = 31, name = "MOD_INCREASE_SPEED", desc = "Increase movement speed", category = "MOVEMENT" },
    { id = 32, name = "MOD_INCREASE_MOUNTED_SPEED", desc = "Increase mounted speed", category = "MOVEMENT" },
    { id = 33, name = "MOD_DECREASE_SPEED", desc = "Decrease movement speed", category = "MOVEMENT" },
    { id = 34, name = "MOD_INCREASE_HEALTH", desc = "Increase health", category = "STAT" },
    { id = 35, name = "MOD_INCREASE_ENERGY", desc = "Increase energy", category = "STAT" },
    { id = 36, name = "MOD_SHAPESHIFT", desc = "Shapeshift form", category = "MISC" },
    { id = 37, name = "EFFECT_IMMUNITY", desc = "Effect immunity", category = "IMMUNITY" },
    { id = 38, name = "STATE_IMMUNITY", desc = "State immunity", category = "IMMUNITY" },
    { id = 39, name = "SCHOOL_IMMUNITY", desc = "School immunity", category = "IMMUNITY" },
    { id = 40, name = "DAMAGE_IMMUNITY", desc = "Damage immunity", category = "IMMUNITY" },
    { id = 41, name = "DISPEL_IMMUNITY", desc = "Dispel immunity", category = "IMMUNITY" },
    { id = 42, name = "PROC_TRIGGER_SPELL", desc = "Proc trigger spell", category = "TRIGGER" },
    { id = 43, name = "PROC_TRIGGER_DAMAGE", desc = "Proc trigger damage", category = "TRIGGER" },
    { id = 44, name = "TRACK_CREATURES", desc = "Track creatures", category = "MISC" },
    { id = 45, name = "TRACK_RESOURCES", desc = "Track resources", category = "MISC" },
    { id = 46, name = "46", desc = "Aura 46", category = "MISC" },
    { id = 47, name = "MOD_PARRY_PERCENT", desc = "Modify parry percent", category = "STAT" },
    { id = 48, name = "48", desc = "Aura 48", category = "MISC" },
    { id = 49, name = "MOD_DODGE_PERCENT", desc = "Modify dodge percent", category = "STAT" },
    { id = 50, name = "MOD_CRITICAL_HEALING_AMOUNT", desc = "Modify crit heal amount", category = "HEAL" },
    { id = 51, name = "MOD_BLOCK_PERCENT", desc = "Modify block percent", category = "STAT" },
    { id = 52, name = "MOD_WEAPON_CRIT_PERCENT", desc = "Modify weapon crit", category = "STAT" },
    { id = 53, name = "PERIODIC_LEECH", desc = "Periodic health leech", category = "DAMAGE" },
    { id = 54, name = "MOD_HIT_CHANCE", desc = "Modify hit chance", category = "STAT" },
    { id = 55, name = "MOD_SPELL_HIT_CHANCE", desc = "Modify spell hit", category = "STAT" },
    { id = 56, name = "TRANSFORM", desc = "Transform into creature", category = "MISC" },
    { id = 57, name = "MOD_SPELL_CRIT_CHANCE", desc = "Modify spell crit", category = "STAT" },
    { id = 58, name = "MOD_INCREASE_SWIM_SPEED", desc = "Increase swim speed", category = "MOVEMENT" },
    { id = 59, name = "MOD_DAMAGE_DONE_CREATURE", desc = "Modify damage vs creature type", category = "DAMAGE" },
    { id = 60, name = "MOD_PACIFY_SILENCE", desc = "Pacify and silence", category = "CONTROL" },
    { id = 61, name = "MOD_SCALE", desc = "Modify scale", category = "MISC" },
    { id = 62, name = "PERIODIC_HEALTH_FUNNEL", desc = "Periodic health funnel", category = "HEAL" },
    { id = 63, name = "63", desc = "Aura 63", category = "MISC" },
    { id = 64, name = "PERIODIC_MANA_LEECH", desc = "Periodic mana leech", category = "POWER" },
    { id = 65, name = "MOD_CASTING_SPEED_NOT_STACK", desc = "Modify cast speed (non-stack)", category = "STAT" },
    { id = 66, name = "FEIGN_DEATH", desc = "Feign death", category = "MISC" },
    { id = 67, name = "MOD_DISARM", desc = "Disarm target", category = "CONTROL" },
    { id = 68, name = "MOD_STALKED", desc = "Stalked effect", category = "MISC" },
    { id = 69, name = "SCHOOL_ABSORB", desc = "Absorb school damage", category = "ABSORB" },
    { id = 70, name = "EXTRA_ATTACKS", desc = "Extra attacks", category = "COMBAT" },
    { id = 71, name = "MOD_SPELL_CRIT_CHANCE_SCHOOL", desc = "Modify spell crit (school)", category = "STAT" },
    { id = 72, name = "MOD_POWER_COST_SCHOOL_PCT", desc = "Modify power cost (school)", category = "STAT" },
    { id = 73, name = "MOD_POWER_COST_SCHOOL", desc = "Modify power cost flat", category = "STAT" },
    { id = 74, name = "REFLECT_SPELLS_SCHOOL", desc = "Reflect spells (school)", category = "COMBAT" },
    { id = 75, name = "MOD_LANGUAGE", desc = "Modify language", category = "MISC" },
    { id = 76, name = "FAR_SIGHT", desc = "Far sight effect", category = "MISC" },
    { id = 77, name = "MECHANIC_IMMUNITY", desc = "Mechanic immunity", category = "IMMUNITY" },
    { id = 78, name = "MOUNTED", desc = "Mounted state", category = "MISC" },
    { id = 79, name = "MOD_DAMAGE_PERCENT_DONE", desc = "Modify damage % done", category = "DAMAGE" },
    { id = 80, name = "MOD_PERCENT_STAT", desc = "Modify stat percent", category = "STAT" },
    { id = 81, name = "SPLIT_DAMAGE_PCT", desc = "Split damage percent", category = "DAMAGE" },
    { id = 82, name = "WATER_BREATHING", desc = "Water breathing", category = "MISC" },
    { id = 83, name = "MOD_BASE_RESISTANCE", desc = "Modify base resistance", category = "STAT" },
    { id = 84, name = "MOD_REGEN", desc = "Modify health regen", category = "HEAL" },
    { id = 85, name = "MOD_POWER_REGEN", desc = "Modify power regen", category = "POWER" },
    { id = 86, name = "CHANNEL_DEATH_ITEM", desc = "Channel death item", category = "MISC" },
    { id = 87, name = "MOD_DAMAGE_PERCENT_TAKEN", desc = "Modify damage % taken", category = "DAMAGE" },
    { id = 88, name = "MOD_HEALTH_REGEN_PERCENT", desc = "Modify health regen %", category = "HEAL" },
    { id = 89, name = "PERIODIC_DAMAGE_PERCENT", desc = "Periodic damage percent", category = "DAMAGE" },
    { id = 90, name = "90", desc = "Aura 90", category = "MISC" },
    { id = 91, name = "MOD_DETECT_RANGE", desc = "Modify detection range", category = "MISC" },
    { id = 92, name = "PREVENTS_FLEEING", desc = "Prevents fleeing", category = "CONTROL" },
    { id = 93, name = "MOD_UNATTACKABLE", desc = "Unattackable", category = "IMMUNITY" },
    { id = 94, name = "INTERRUPT_REGEN", desc = "Interrupt regeneration", category = "MISC" },
    { id = 95, name = "GHOST", desc = "Ghost state", category = "MISC" },
    { id = 96, name = "SPELL_MAGNET", desc = "Spell magnet", category = "COMBAT" },
    { id = 97, name = "MANA_SHIELD", desc = "Mana shield", category = "ABSORB" },
    { id = 98, name = "MOD_SKILL_TALENT", desc = "Modify skill talent", category = "STAT" },
    { id = 99, name = "MOD_ATTACK_POWER", desc = "Modify attack power", category = "STAT" },
    { id = 100, name = "AURAS_VISIBLE", desc = "Auras visible", category = "MISC" },
    { id = 101, name = "MOD_RESISTANCE_PCT", desc = "Modify resistance %", category = "STAT" },
    { id = 102, name = "MOD_MELEE_ATTACK_POWER_VERSUS", desc = "Modify melee AP vs", category = "STAT" },
    { id = 103, name = "MOD_TOTAL_THREAT", desc = "Modify total threat", category = "COMBAT" },
    { id = 104, name = "WATER_WALK", desc = "Water walking", category = "MOVEMENT" },
    { id = 105, name = "FEATHER_FALL", desc = "Feather fall", category = "MOVEMENT" },
    { id = 106, name = "HOVER", desc = "Hover effect", category = "MOVEMENT" },
    { id = 107, name = "ADD_FLAT_MODIFIER", desc = "Add flat spell modifier", category = "STAT" },
    { id = 108, name = "ADD_PCT_MODIFIER", desc = "Add percent spell modifier", category = "STAT" },
    { id = 109, name = "ADD_TARGET_TRIGGER", desc = "Add target trigger", category = "TRIGGER" },
    { id = 110, name = "MOD_POWER_REGEN_PERCENT", desc = "Modify power regen %", category = "POWER" },
    { id = 111, name = "ADD_CASTER_HIT_TRIGGER", desc = "Add caster hit trigger", category = "TRIGGER" },
    { id = 112, name = "OVERRIDE_CLASS_SCRIPTS", desc = "Override class scripts", category = "MISC" },
    { id = 113, name = "MOD_RANGED_DAMAGE_TAKEN", desc = "Modify ranged damage taken", category = "DAMAGE" },
    { id = 114, name = "MOD_RANGED_DAMAGE_TAKEN_PCT", desc = "Modify ranged damage taken %", category = "DAMAGE" },
    { id = 115, name = "MOD_HEALING", desc = "Modify healing done", category = "HEAL" },
    { id = 116, name = "MOD_REGEN_DURING_COMBAT", desc = "Modify regen in combat", category = "HEAL" },
    { id = 117, name = "MOD_MECHANIC_RESISTANCE", desc = "Modify mechanic resistance", category = "STAT" },
    { id = 118, name = "MOD_HEALING_PCT", desc = "Modify healing %", category = "HEAL" },
    { id = 119, name = "119", desc = "Aura 119", category = "MISC" },
    { id = 120, name = "UNTRACKABLE", desc = "Untrackable", category = "MISC" },
    { id = 121, name = "EMPATHY", desc = "Empathy (beast)", category = "MISC" },
    { id = 122, name = "MOD_OFFHAND_DAMAGE_PCT", desc = "Modify offhand damage %", category = "DAMAGE" },
    { id = 123, name = "MOD_TARGET_RESISTANCE", desc = "Modify target resistance", category = "STAT" },
    { id = 124, name = "MOD_RANGED_ATTACK_POWER", desc = "Modify ranged AP", category = "STAT" },
    { id = 125, name = "MOD_MELEE_DAMAGE_TAKEN", desc = "Modify melee damage taken", category = "DAMAGE" },
    { id = 126, name = "MOD_MELEE_DAMAGE_TAKEN_PCT", desc = "Modify melee damage taken %", category = "DAMAGE" },
    { id = 127, name = "RANGED_ATTACK_POWER_ATTACKER_BONUS", desc = "Ranged AP attacker bonus", category = "STAT" },
    { id = 128, name = "MOD_POSSESS_PET", desc = "Possess pet", category = "CONTROL" },
    { id = 129, name = "MOD_SPEED_ALWAYS", desc = "Modify speed (always)", category = "MOVEMENT" },
    { id = 130, name = "MOD_MOUNTED_SPEED_ALWAYS", desc = "Modify mounted speed (always)", category = "MOVEMENT" },
    { id = 131, name = "MOD_RANGED_ATTACK_POWER_VERSUS", desc = "Modify ranged AP vs", category = "STAT" },
    { id = 132, name = "MOD_INCREASE_ENERGY_PERCENT", desc = "Modify energy %", category = "STAT" },
    { id = 133, name = "MOD_INCREASE_HEALTH_PERCENT", desc = "Modify health %", category = "STAT" },
    { id = 134, name = "MOD_MANA_REGEN_INTERRUPT", desc = "Modify mana regen interrupt", category = "POWER" },
    { id = 135, name = "MOD_HEALING_DONE", desc = "Modify healing done", category = "HEAL" },
    { id = 136, name = "MOD_HEALING_DONE_PERCENT", desc = "Modify healing done %", category = "HEAL" },
    { id = 137, name = "MOD_TOTAL_STAT_PERCENTAGE", desc = "Modify total stat %", category = "STAT" },
    { id = 138, name = "MOD_MELEE_HASTE", desc = "Modify melee haste", category = "STAT" },
    { id = 139, name = "FORCE_REACTION", desc = "Force reaction", category = "MISC" },
    { id = 140, name = "MOD_RANGED_HASTE", desc = "Modify ranged haste", category = "STAT" },
    { id = 141, name = "MOD_RANGED_AMMO_HASTE", desc = "Modify ranged ammo haste", category = "STAT" },
    { id = 142, name = "MOD_BASE_RESISTANCE_PCT", desc = "Modify base resistance %", category = "STAT" },
    { id = 143, name = "MOD_RESISTANCE_EXCLUSIVE", desc = "Modify resistance exclusive", category = "STAT" },
    { id = 144, name = "SAFE_FALL", desc = "Safe fall", category = "MOVEMENT" },
    { id = 145, name = "MOD_PET_TALENT_POINTS", desc = "Modify pet talent points", category = "STAT" },
    { id = 146, name = "ALLOW_TAME_PET_TYPE", desc = "Allow tame pet type", category = "MISC" },
    { id = 147, name = "MECHANIC_IMMUNITY_MASK", desc = "Mechanic immunity mask", category = "IMMUNITY" },
    { id = 148, name = "RETAIN_COMBO_POINTS", desc = "Retain combo points", category = "COMBAT" },
    { id = 149, name = "REDUCE_PUSHBACK", desc = "Reduce pushback", category = "STAT" },
    { id = 150, name = "MOD_SHIELD_BLOCKVALUE_PCT", desc = "Modify shield block %", category = "STAT" },
    { id = 151, name = "TRACK_STEALTHED", desc = "Track stealthed", category = "MISC" },
    { id = 152, name = "MOD_DETECTED_RANGE", desc = "Modify detected range", category = "MISC" },
    { id = 153, name = "SPLIT_DAMAGE_FLAT", desc = "Split damage flat", category = "DAMAGE" },
    { id = 154, name = "MOD_STEALTH_LEVEL", desc = "Modify stealth level", category = "MISC" },
    { id = 155, name = "MOD_WATER_BREATHING", desc = "Modify water breathing", category = "MISC" },
    { id = 156, name = "MOD_REPUTATION_GAIN", desc = "Modify reputation gain", category = "MISC" },
    { id = 157, name = "PET_DAMAGE_MULTI", desc = "Pet damage multiplier", category = "DAMAGE" },
    { id = 158, name = "MOD_SHIELD_BLOCKVALUE", desc = "Modify shield block value", category = "STAT" },
    { id = 159, name = "NO_PVP_CREDIT", desc = "No PvP credit", category = "MISC" },
    { id = 160, name = "MOD_AOE_AVOIDANCE", desc = "Modify AoE avoidance", category = "STAT" },
    { id = 161, name = "MOD_HEALTH_REGEN_IN_COMBAT", desc = "Modify health regen in combat", category = "HEAL" },
    { id = 162, name = "POWER_BURN", desc = "Power burn", category = "POWER" },
    { id = 163, name = "MOD_CRIT_DAMAGE_BONUS", desc = "Modify crit damage bonus", category = "DAMAGE" },
    { id = 164, name = "164", desc = "Aura 164", category = "MISC" },
    { id = 165, name = "MELEE_ATTACK_POWER_ATTACKER_BONUS", desc = "Melee AP attacker bonus", category = "STAT" },
    { id = 166, name = "MOD_ATTACK_POWER_PCT", desc = "Modify attack power %", category = "STAT" },
    { id = 167, name = "MOD_RANGED_ATTACK_POWER_PCT", desc = "Modify ranged AP %", category = "STAT" },
    { id = 168, name = "MOD_DAMAGE_DONE_VERSUS", desc = "Modify damage vs creature", category = "DAMAGE" },
    { id = 169, name = "MOD_CRIT_PERCENT_VERSUS", desc = "Modify crit % vs creature", category = "STAT" },
    { id = 170, name = "DETECT_AMORE", desc = "Detect amore", category = "MISC" },
    { id = 171, name = "MOD_SPEED_NOT_STACK", desc = "Modify speed (non-stack)", category = "MOVEMENT" },
    { id = 172, name = "MOD_MOUNTED_SPEED_NOT_STACK", desc = "Modify mounted speed (non-stack)", category = "MOVEMENT" },
    { id = 173, name = "173", desc = "Aura 173", category = "MISC" },
    { id = 174, name = "MOD_SPELL_DAMAGE_OF_STAT_PERCENT", desc = "Spell damage from stat %", category = "STAT" },
    { id = 175, name = "MOD_SPELL_HEALING_OF_STAT_PERCENT", desc = "Spell healing from stat %", category = "STAT" },
    { id = 176, name = "SPIRIT_OF_REDEMPTION", desc = "Spirit of Redemption", category = "MISC" },
    { id = 177, name = "AOE_CHARM", desc = "AoE charm", category = "CONTROL" },
    { id = 178, name = "MOD_DEBUFF_RESISTANCE", desc = "Modify debuff resistance", category = "STAT" },
    { id = 179, name = "MOD_ATTACKER_SPELL_CRIT_CHANCE", desc = "Modify attacker spell crit", category = "STAT" },
    { id = 180, name = "MOD_FLAT_SPELL_DAMAGE_VERSUS", desc = "Modify flat spell damage vs", category = "DAMAGE" },
    { id = 181, name = "181", desc = "Aura 181", category = "MISC" },
    { id = 182, name = "MOD_RESISTANCE_OF_STAT_PERCENT", desc = "Resistance from stat %", category = "STAT" },
    { id = 183, name = "MOD_CRITICAL_THREAT", desc = "Modify critical threat", category = "COMBAT" },
    { id = 184, name = "MOD_ATTACKER_MELEE_HIT_CHANCE", desc = "Modify attacker melee hit", category = "STAT" },
    { id = 185, name = "MOD_ATTACKER_RANGED_HIT_CHANCE", desc = "Modify attacker ranged hit", category = "STAT" },
    { id = 186, name = "MOD_ATTACKER_SPELL_HIT_CHANCE", desc = "Modify attacker spell hit", category = "STAT" },
    { id = 187, name = "MOD_ATTACKER_MELEE_CRIT_CHANCE", desc = "Modify attacker melee crit", category = "STAT" },
    { id = 188, name = "MOD_ATTACKER_RANGED_CRIT_CHANCE", desc = "Modify attacker ranged crit", category = "STAT" },
    { id = 189, name = "MOD_RATING", desc = "Modify rating", category = "STAT" },
    { id = 190, name = "MOD_FACTION_REPUTATION_GAIN", desc = "Modify faction rep gain", category = "MISC" },
    { id = 191, name = "USE_NORMAL_MOVEMENT_SPEED", desc = "Use normal movement speed", category = "MOVEMENT" },
    { id = 192, name = "MOD_MELEE_RANGED_HASTE", desc = "Modify melee/ranged haste", category = "STAT" },
    { id = 193, name = "MELEE_SLOW", desc = "Melee slow", category = "STAT" },
    { id = 194, name = "MOD_TARGET_ABSORB_SCHOOL", desc = "Modify target absorb school", category = "ABSORB" },
    { id = 195, name = "MOD_TARGET_ABILITY_ABSORB_SCHOOL", desc = "Modify target ability absorb", category = "ABSORB" },
    { id = 196, name = "MOD_COOLDOWN", desc = "Modify cooldown", category = "STAT" },
    { id = 197, name = "MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE", desc = "Modify attacker crit chance", category = "STAT" },
    { id = 198, name = "198", desc = "Aura 198", category = "MISC" },
    { id = 199, name = "MOD_INCREASES_SPELL_PCT_TO_HIT", desc = "Modify spell % to hit", category = "STAT" },
    { id = 200, name = "MOD_XP_PCT", desc = "Modify XP %", category = "MISC" },
    { id = 201, name = "FLY", desc = "Fly aura", category = "MOVEMENT" },
    { id = 202, name = "IGNORE_COMBAT_RESULT", desc = "Ignore combat result", category = "COMBAT" },
    { id = 203, name = "MOD_ATTACKER_MELEE_CRIT_DAMAGE", desc = "Modify attacker melee crit damage", category = "DAMAGE" },
    { id = 204, name = "MOD_ATTACKER_RANGED_CRIT_DAMAGE", desc = "Modify attacker ranged crit damage", category = "DAMAGE" },
    { id = 205, name = "MOD_SCHOOL_CRIT_DMG_TAKEN", desc = "Modify school crit damage taken", category = "DAMAGE" },
    { id = 206, name = "MOD_INCREASE_VEHICLE_FLIGHT_SPEED", desc = "Modify vehicle flight speed", category = "MOVEMENT" },
    { id = 207, name = "MOD_INCREASE_MOUNTED_FLIGHT_SPEED", desc = "Modify mounted flight speed", category = "MOVEMENT" },
    { id = 208, name = "MOD_INCREASE_FLIGHT_SPEED", desc = "Modify flight speed", category = "MOVEMENT" },
    { id = 209, name = "MOD_MOUNTED_FLIGHT_SPEED_ALWAYS", desc = "Modify mounted flight speed (always)", category = "MOVEMENT" },
    { id = 210, name = "MOD_VEHICLE_SPEED_ALWAYS", desc = "Modify vehicle speed (always)", category = "MOVEMENT" },
    { id = 211, name = "MOD_FLIGHT_SPEED_NOT_STACK", desc = "Modify flight speed (non-stack)", category = "MOVEMENT" },
    { id = 212, name = "MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT", desc = "Ranged AP from stat %", category = "STAT" },
    { id = 213, name = "MOD_RAGE_FROM_DAMAGE_DEALT", desc = "Modify rage from damage", category = "POWER" },
    { id = 214, name = "214", desc = "Aura 214", category = "MISC" },
    { id = 215, name = "ARENA_PREPARATION", desc = "Arena preparation", category = "MISC" },
    { id = 216, name = "HASTE_SPELLS", desc = "Haste spells", category = "STAT" },
    { id = 217, name = "MOD_MELEE_HASTE_2", desc = "Modify melee haste (type 2)", category = "STAT" },
    { id = 218, name = "HASTE_RANGED", desc = "Haste ranged", category = "STAT" },
    { id = 219, name = "MOD_MANA_REGEN_FROM_STAT", desc = "Mana regen from stat", category = "POWER" },
    { id = 220, name = "MOD_RATING_FROM_STAT", desc = "Rating from stat", category = "STAT" },
    { id = 221, name = "MOD_DETAUNT", desc = "Modify detaunt", category = "COMBAT" },
    { id = 222, name = "222", desc = "Aura 222", category = "MISC" },
    { id = 223, name = "RAID_PROC_FROM_CHARGE", desc = "Raid proc from charge", category = "TRIGGER" },
    { id = 224, name = "224", desc = "Aura 224", category = "MISC" },
    { id = 225, name = "RAID_PROC_FROM_CHARGE_WITH_VALUE", desc = "Raid proc from charge with value", category = "TRIGGER" },
    { id = 226, name = "PERIODIC_DUMMY", desc = "Periodic dummy", category = "MISC" },
    { id = 227, name = "PERIODIC_TRIGGER_SPELL_WITH_VALUE", desc = "Periodic trigger spell with value", category = "TRIGGER" },
    { id = 228, name = "DETECT_STEALTH", desc = "Detect stealth", category = "MISC" },
    { id = 229, name = "MOD_AOE_DAMAGE_AVOIDANCE", desc = "Modify AoE damage avoidance", category = "STAT" },
    { id = 230, name = "230", desc = "Aura 230", category = "MISC" },
    { id = 231, name = "PROC_TRIGGER_SPELL_WITH_VALUE", desc = "Proc trigger spell with value", category = "TRIGGER" },
    { id = 232, name = "MECHANIC_DURATION_MOD", desc = "Mechanic duration modifier", category = "STAT" },
    { id = 233, name = "CHANGE_MODEL_FOR_ALL_HUMANOIDS", desc = "Change model for all humanoids", category = "MISC" },
    { id = 234, name = "MECHANIC_DURATION_MOD_NOT_STACK", desc = "Mechanic duration mod (non-stack)", category = "STAT" },
    { id = 235, name = "MOD_DISPEL_RESIST", desc = "Modify dispel resist", category = "STAT" },
    { id = 236, name = "CONTROL_VEHICLE", desc = "Control vehicle", category = "CONTROL" },
    { id = 237, name = "MOD_SPELL_DAMAGE_OF_ATTACK_POWER", desc = "Spell damage from AP", category = "STAT" },
    { id = 238, name = "MOD_SPELL_HEALING_OF_ATTACK_POWER", desc = "Spell healing from AP", category = "STAT" },
    { id = 239, name = "MOD_SCALE_2", desc = "Modify scale (type 2)", category = "MISC" },
    { id = 240, name = "MOD_EXPERTISE", desc = "Modify expertise", category = "STAT" },
    { id = 241, name = "FORCE_MOVE_FORWARD", desc = "Force move forward", category = "MOVEMENT" },
    { id = 242, name = "MOD_SPELL_DAMAGE_FROM_HEALING", desc = "Spell damage from healing", category = "STAT" },
    { id = 243, name = "MOD_FACTION", desc = "Modify faction", category = "MISC" },
    { id = 244, name = "COMPREHEND_LANGUAGE", desc = "Comprehend language", category = "MISC" },
    { id = 245, name = "MOD_AURA_DURATION_BY_DISPEL", desc = "Modify aura duration by dispel", category = "STAT" },
    { id = 246, name = "MOD_AURA_DURATION_BY_DISPEL_NOT_STACK", desc = "Modify aura duration by dispel (non-stack)", category = "STAT" },
    { id = 247, name = "CLONE_CASTER", desc = "Clone caster", category = "MISC" },
    { id = 248, name = "MOD_COMBAT_RESULT_CHANCE", desc = "Modify combat result chance", category = "COMBAT" },
    { id = 249, name = "CONVERT_RUNE", desc = "Convert rune", category = "MISC" },
    { id = 250, name = "MOD_INCREASE_HEALTH_2", desc = "Modify health (type 2)", category = "STAT" },
    { id = 251, name = "MOD_ENEMY_DODGE", desc = "Modify enemy dodge", category = "STAT" },
    { id = 252, name = "MOD_SPEED_SLOW_ALL", desc = "Modify speed slow all", category = "MOVEMENT" },
    { id = 253, name = "MOD_BLOCK_CRIT_CHANCE", desc = "Modify block crit chance", category = "STAT" },
    { id = 254, name = "MOD_DISARM_OFFHAND", desc = "Disarm offhand", category = "CONTROL" },
    { id = 255, name = "MOD_MECHANIC_DAMAGE_TAKEN_PERCENT", desc = "Modify mechanic damage taken %", category = "DAMAGE" },
    { id = 256, name = "NO_REAGENT_USE", desc = "No reagent use", category = "MISC" },
    { id = 257, name = "MOD_TARGET_RESIST_BY_SPELL_CLASS", desc = "Modify target resist by spell class", category = "STAT" },
    { id = 258, name = "258", desc = "Aura 258", category = "MISC" },
    { id = 259, name = "MOD_HOT_PCT", desc = "Modify HoT %", category = "HEAL" },
    { id = 260, name = "SCREEN_EFFECT", desc = "Screen effect", category = "MISC" },
    { id = 261, name = "PHASE", desc = "Phase effect", category = "MISC" },
    { id = 262, name = "ABILITY_IGNORE_AURASTATE", desc = "Ability ignore aura state", category = "MISC" },
    { id = 263, name = "ALLOW_ONLY_ABILITY", desc = "Allow only ability", category = "MISC" },
    { id = 264, name = "264", desc = "Aura 264", category = "MISC" },
    { id = 265, name = "265", desc = "Aura 265", category = "MISC" },
    { id = 266, name = "266", desc = "Aura 266", category = "MISC" },
    { id = 267, name = "MOD_IMMUNE_AURA_APPLY_SCHOOL", desc = "Modify immune aura apply school", category = "IMMUNITY" },
    { id = 268, name = "MOD_ATTACK_POWER_OF_STAT_PERCENT", desc = "AP from stat %", category = "STAT" },
    { id = 269, name = "MOD_IGNORE_TARGET_RESIST", desc = "Modify ignore target resist", category = "STAT" },
    { id = 270, name = "MOD_ABILITY_IGNORE_TARGET_RESIST", desc = "Modify ability ignore target resist", category = "STAT" },
    { id = 271, name = "MOD_DAMAGE_FROM_CASTER", desc = "Modify damage from caster", category = "DAMAGE" },
    { id = 272, name = "IGNORE_MELEE_RESET", desc = "Ignore melee reset", category = "COMBAT" },
    { id = 273, name = "X_RAY", desc = "X-ray vision", category = "MISC" },
    { id = 274, name = "ABILITY_CONSUME_NO_AMMO", desc = "Ability consumes no ammo", category = "MISC" },
    { id = 275, name = "MOD_IGNORE_SHAPESHIFT", desc = "Modify ignore shapeshift", category = "MISC" },
    { id = 276, name = "MOD_DAMAGE_DONE_FOR_MECHANIC", desc = "Modify damage done for mechanic", category = "DAMAGE" },
    { id = 277, name = "MOD_MAX_AFFECTED_TARGETS", desc = "Modify max affected targets", category = "STAT" },
    { id = 278, name = "MOD_DISARM_RANGED", desc = "Disarm ranged", category = "CONTROL" },
    { id = 279, name = "INITIALIZE_IMAGES", desc = "Initialize images", category = "MISC" },
    { id = 280, name = "MOD_ARMOR_PENETRATION_PCT", desc = "Modify armor penetration %", category = "STAT" },
    { id = 281, name = "MOD_HONOR_GAIN_PCT", desc = "Modify honor gain %", category = "MISC" },
    { id = 282, name = "MOD_BASE_HEALTH_PCT", desc = "Modify base health %", category = "STAT" },
    { id = 283, name = "MOD_HEALING_RECEIVED", desc = "Modify healing received", category = "HEAL" },
    { id = 284, name = "LINKED", desc = "Linked aura", category = "MISC" },
    { id = 285, name = "MOD_ATTACK_POWER_OF_ARMOR", desc = "AP from armor", category = "STAT" },
    { id = 286, name = "ABILITY_PERIODIC_CRIT", desc = "Ability periodic crit", category = "STAT" },
    { id = 287, name = "DEFLECT_SPELLS", desc = "Deflect spells", category = "COMBAT" },
    { id = 288, name = "IGNORE_HIT_DIRECTION", desc = "Ignore hit direction", category = "COMBAT" },
    { id = 289, name = "289", desc = "Aura 289", category = "MISC" },
    { id = 290, name = "MOD_CRIT_PCT", desc = "Modify crit %", category = "STAT" },
    { id = 291, name = "MOD_XP_QUEST_PCT", desc = "Modify quest XP %", category = "MISC" },
    { id = 292, name = "OPEN_STABLE", desc = "Open stable", category = "MISC" },
    { id = 293, name = "OVERRIDE_SPELLS", desc = "Override spells", category = "MISC" },
    { id = 294, name = "PREVENT_REGENERATE_POWER", desc = "Prevent power regeneration", category = "POWER" },
    { id = 295, name = "295", desc = "Aura 295", category = "MISC" },
    { id = 296, name = "SET_VEHICLE_ID", desc = "Set vehicle ID", category = "MISC" },
    { id = 297, name = "BLOCK_SPELL_FAMILY", desc = "Block spell family", category = "MISC" },
    { id = 298, name = "STRANGULATE", desc = "Strangulate", category = "CONTROL" },
    { id = 299, name = "299", desc = "Aura 299", category = "MISC" },
    { id = 300, name = "SHARE_DAMAGE_PCT", desc = "Share damage %", category = "DAMAGE" },
    { id = 301, name = "SCHOOL_HEAL_ABSORB", desc = "School heal absorb", category = "ABSORB" },
    { id = 302, name = "302", desc = "Aura 302", category = "MISC" },
    { id = 303, name = "MOD_DAMAGE_DONE_VERSUS_AURASTATE", desc = "Modify damage vs aura state", category = "DAMAGE" },
    { id = 304, name = "MOD_FAKE_INEBRIATE", desc = "Modify fake inebriate", category = "MISC" },
    { id = 305, name = "MOD_MINIMUM_SPEED", desc = "Modify minimum speed", category = "MOVEMENT" },
    { id = 306, name = "306", desc = "Aura 306", category = "MISC" },
    { id = 307, name = "HEAL_ABSORB_TEST", desc = "Heal absorb test", category = "ABSORB" },
    { id = 308, name = "MOD_CRIT_CHANCE_FOR_CASTER", desc = "Modify crit chance for caster", category = "STAT" },
    { id = 309, name = "309", desc = "Aura 309", category = "MISC" },
    { id = 310, name = "MOD_CREATURE_AOE_DAMAGE_AVOIDANCE", desc = "Modify creature AoE damage avoidance", category = "STAT" },
    { id = 311, name = "311", desc = "Aura 311", category = "MISC" },
    { id = 312, name = "312", desc = "Aura 312", category = "MISC" },
    { id = 313, name = "313", desc = "Aura 313", category = "MISC" },
    { id = 314, name = "PREVENT_RESURRECTION", desc = "Prevent resurrection", category = "MISC" },
    { id = 315, name = "UNDERWATER_WALKING", desc = "Underwater walking", category = "MOVEMENT" },
    { id = 316, name = "PERIODIC_HASTE", desc = "Periodic haste", category = "STAT" },
}

-- ============================================================================
-- SPELL TARGET TYPES
-- ============================================================================
_G.ENUM_DATA.SPELL_TARGETS = {
    { id = 0, name = "TARGET_NONE", desc = "No target", category = "NONE" },
    { id = 1, name = "TARGET_UNIT_CASTER", desc = "Self (caster)", category = "SELF" },
    { id = 2, name = "TARGET_UNIT_NEARBY_ENEMY", desc = "Nearby enemy unit", category = "ENEMY" },
    { id = 3, name = "TARGET_UNIT_NEARBY_PARTY", desc = "Nearby party member", category = "PARTY" },
    { id = 4, name = "TARGET_UNIT_NEARBY_ALLY", desc = "Nearby ally", category = "ALLY" },
    { id = 5, name = "TARGET_UNIT_PET", desc = "Caster's pet", category = "PET" },
    { id = 6, name = "TARGET_UNIT_TARGET_ENEMY", desc = "Selected enemy", category = "ENEMY" },
    { id = 7, name = "TARGET_UNIT_SRC_AREA_ENTRY", desc = "Scriptable entry target", category = "AREA" },
    { id = 8, name = "TARGET_UNIT_DEST_AREA_ENTRY", desc = "Destination area entry", category = "AREA" },
    { id = 9, name = "TARGET_DEST_HOME", desc = "Home location", category = "DEST" },
    { id = 11, name = "TARGET_UNIT_SRC_AREA_ENEMY", desc = "Enemies in source area", category = "AREA" },
    { id = 15, name = "TARGET_UNIT_DEST_AREA_ENEMY", desc = "Enemies at destination", category = "AREA" },
    { id = 16, name = "TARGET_DEST_DB", desc = "Database destination", category = "DEST" },
    { id = 17, name = "TARGET_DEST_CASTER", desc = "Caster location", category = "DEST" },
    { id = 20, name = "TARGET_UNIT_CASTER_AREA_PARTY", desc = "Party around caster", category = "PARTY" },
    { id = 21, name = "TARGET_UNIT_TARGET_ALLY", desc = "Selected ally", category = "ALLY" },
    { id = 22, name = "TARGET_SRC_CASTER", desc = "Source is caster", category = "SELF" },
    { id = 23, name = "TARGET_GAMEOBJECT_TARGET", desc = "Selected game object", category = "OBJECT" },
    { id = 24, name = "TARGET_UNIT_CONE_ENEMY", desc = "Enemies in cone", category = "CONE" },
    { id = 25, name = "TARGET_UNIT_TARGET_ANY", desc = "Any selected target", category = "ANY" },
    { id = 26, name = "TARGET_GAMEOBJECT_ITEM_TARGET", desc = "Item target", category = "ITEM" },
    { id = 27, name = "TARGET_UNIT_MASTER", desc = "Master/Owner", category = "OWNER" },
    { id = 28, name = "TARGET_DEST_DYNOBJ_ENEMY", desc = "Dynamic object enemies", category = "AREA" },
    { id = 29, name = "TARGET_DEST_DYNOBJ_ALLY", desc = "Dynamic object allies", category = "AREA" },
    { id = 30, name = "TARGET_UNIT_SRC_AREA_ALLY", desc = "Allies in source area", category = "AREA" },
    { id = 31, name = "TARGET_UNIT_DEST_AREA_ALLY", desc = "Allies at destination", category = "AREA" },
    { id = 32, name = "TARGET_DEST_CASTER_SUMMON", desc = "Summon location", category = "SUMMON" },
    { id = 33, name = "TARGET_UNIT_SRC_AREA_PARTY", desc = "Party in source area", category = "PARTY" },
    { id = 34, name = "TARGET_UNIT_DEST_AREA_PARTY", desc = "Party at destination", category = "PARTY" },
    { id = 35, name = "TARGET_UNIT_TARGET_PARTY", desc = "Target's party", category = "PARTY" },
    { id = 37, name = "TARGET_UNIT_TARGET_CHAINHEAL", desc = "Chain heal targets", category = "HEAL" },
    { id = 38, name = "TARGET_DEST_CHANNEL_TARGET", desc = "Channeled spell target", category = "CHANNEL" },
    { id = 39, name = "TARGET_UNIT_CHANNEL_TARGET", desc = "Channel target unit", category = "CHANNEL" },
    { id = 41, name = "TARGET_DEST_DEST_FRONT", desc = "In front of dest", category = "DEST" },
    { id = 42, name = "TARGET_DEST_DEST_BACK", desc = "Behind dest", category = "DEST" },
    { id = 43, name = "TARGET_DEST_DEST_RIGHT", desc = "Right of dest", category = "DEST" },
    { id = 44, name = "TARGET_DEST_DEST_LEFT", desc = "Left of dest", category = "DEST" },
    { id = 45, name = "TARGET_DEST_DEST_FRONT_RIGHT", desc = "Front-right of dest", category = "DEST" },
    { id = 46, name = "TARGET_DEST_DEST_BACK_RIGHT", desc = "Back-right of dest", category = "DEST" },
    { id = 47, name = "TARGET_DEST_DEST_BACK_LEFT", desc = "Back-left of dest", category = "DEST" },
    { id = 48, name = "TARGET_DEST_DEST_FRONT_LEFT", desc = "Front-left of dest", category = "DEST" },
    { id = 49, name = "TARGET_DEST_DEST_RANDOM", desc = "Random around dest", category = "DEST" },
    { id = 50, name = "TARGET_DEST_DEST", desc = "Destination", category = "DEST" },
    { id = 52, name = "TARGET_DEST_TRAJ", desc = "Trajectory destination", category = "DEST" },
    { id = 53, name = "TARGET_UNIT_TARGET_MINIPET", desc = "Target minipet", category = "PET" },
    { id = 54, name = "TARGET_DEST_DEST_RADIUS", desc = "Radius around dest", category = "AREA" },
    { id = 55, name = "TARGET_UNIT_SUMMONER", desc = "Summoner", category = "OWNER" },
    { id = 56, name = "TARGET_CORPSE_SRC_AREA_ENEMY", desc = "Enemy corpses in area", category = "CORPSE" },
    { id = 57, name = "TARGET_UNIT_VEHICLE", desc = "Vehicle", category = "VEHICLE" },
    { id = 58, name = "TARGET_UNIT_TARGET_PASSENGER", desc = "Vehicle passenger", category = "VEHICLE" },
    { id = 59, name = "TARGET_UNIT_PASSENGER_0", desc = "Passenger slot 0", category = "VEHICLE" },
    { id = 60, name = "TARGET_UNIT_PASSENGER_1", desc = "Passenger slot 1", category = "VEHICLE" },
    { id = 61, name = "TARGET_UNIT_PASSENGER_2", desc = "Passenger slot 2", category = "VEHICLE" },
    { id = 62, name = "TARGET_UNIT_PASSENGER_3", desc = "Passenger slot 3", category = "VEHICLE" },
    { id = 63, name = "TARGET_UNIT_PASSENGER_4", desc = "Passenger slot 4", category = "VEHICLE" },
    { id = 64, name = "TARGET_UNIT_PASSENGER_5", desc = "Passenger slot 5", category = "VEHICLE" },
    { id = 65, name = "TARGET_UNIT_PASSENGER_6", desc = "Passenger slot 6", category = "VEHICLE" },
    { id = 66, name = "TARGET_UNIT_PASSENGER_7", desc = "Passenger slot 7", category = "VEHICLE" },
    { id = 67, name = "TARGET_UNIT_CONE_ENTRY", desc = "Cone entry target", category = "CONE" },
    { id = 77, name = "TARGET_UNIT_CASTER_AREA_RAID", desc = "Raid around caster", category = "RAID" },
    { id = 86, name = "TARGET_UNIT_TARGET_RAID_CLASS", desc = "Raid class target", category = "RAID" },
    { id = 87, name = "TARGET_DEST_CASTER_GROUND", desc = "Ground at caster", category = "DEST" },
    { id = 89, name = "TARGET_DEST_CASTER_FRONT", desc = "In front of caster", category = "DEST" },
    { id = 90, name = "TARGET_DEST_CASTER_BACK", desc = "Behind caster", category = "DEST" },
    { id = 104, name = "TARGET_UNIT_CONE_ALLY", desc = "Allies in cone", category = "CONE" },
    { id = 110, name = "TARGET_UNIT_NEARBY_RAID", desc = "Nearby raid member", category = "RAID" },
}

-- Helper function to get enum data by type
function GetEnumData(enumType)
    return _G.ENUM_DATA[enumType]
end

-- Export
_G.GetEnumData = GetEnumData

-- print("|cFF00FF00[UIStyleLibrary] EnumData loaded|r")
